name: Directory as shared area
on: push
jobs:
  test-dir:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create dir
        run: mkdir /mydata
      
      - name: List data
        continue-on-error: true
        run: ls -l /mydata

      - name: Get data
        run: echo "This is in the file" > /mydata/somedata

      - name: Do something with data
        run: cat /mydata/somedata