name: Directory as shared area
on: push
jobs:
  test-dir:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create dir
        run: |
          whoami
          pwd
          mkdir mydata

      - name: Get data
        run: echo "This is in the file" > mydata/somedata

      - name: List data
        run: ls -l mydata

      - name: Use data
        run: cat mydata/somedata