name: Caching data

on: push

jobs:
  test-cache:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache data
      id: cache-data
      uses: actions/cache@v3
      with:
        path: cached-data
        key: ${{ runner.os }}-cached-data

    - name: Generate data
      if: steps.cache-data.outputs.cache-hit != 'true'
      run: | 
        pwd
        ls -l
        echo "This is data" > cached-data

    - name: List data
      run: ls -l cached-data

    - name: Use data
      run: cat cached-data