name: Caching data

on: push

jobs:
  test-cache:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

## NB this worked with "path" cached-data and the file created with echo "This is data" > cached-data
## in the next step. 
    - name: Cache data
      id: cache-data
      uses: actions/cache@v3
      with:
        path: | 
          cached-data
          metadata.json
        key: ${{ runner.os }}-cached-data

    - name: Generate data
      if: steps.cache-data.outputs.cache-hit != 'true'
      run: | 
        pwd
        ls -l
        echo "This is data" > cached-data
        docker run --rm cernopendata/cernopendata-client:0.3.0 get-metadata --recid 24103 > metadata.json
        

    - name: List data
      run: ls -l 

    - name: Use data
      run: cat cached-data