name: Directory as shared area
on: push
jobs:
  test-dir:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create dir
        run: |
          mkdir mydata

# I have not found out how to pass the volume with steps with "uses:" 
# "volumes: mydata:/code" in the following has no effect (and is invalid)
# Probably easiest to go back to brute force "docker run"...
      - name: Get the full metadata 
        uses: docker://cernopendata/cernopendata-client:0.3.0
        with:
          args: get-metadata --recid 24103

      - name: Download a file
        uses: docker://cernopendata/cernopendata-client:0.3.0
        with:
          args: --workdir /code -v mydata:/code download-files --recid 1002

      - name: Get data
        run: echo "This is in the file" > mydata/somedata

      - name: List data
        run: ls -l mydata

      - name: Use data
        run: cat mydata/somedata