name: Directory as shared area
on: push
jobs:
  test-dir:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create dir
        run: |
          mkdir mydata

# I have not found out how to pass the volume with steps with "uses:" 
# "volumes: mydata:/code" has no effect (and is invalid)
# Going back to brute force "docker run"...
      - name: Get the full metadata 
        run: |
          pwd
          ls -l
          docker run --rm cernopendata/cernopendata-client:0.3.0 get-metadata --recid 24103 > mydata/metadata.json
          docker run --rm cernopendata/cernopendata-client:0.3.0 get-file-locations --recid 24103 --protocol xrootd> mydata/file-locations.json

      - name: Read parameters from metadata
        run: |
          which python
          which python3
          python read_metadata.py > mydata/var.sh

      - name: Download a the validated runs file
        run: |
          pwd
          source var.sh
          docker run --rm -v $PWD/mydata:/code -u root cernopendata/cernopendata-client:0.3.0 download-files --recid $VALI_RECID --protocol xrootd

      - name: List data
        run: | 
          pwd
          ls -l mydata
          cat mydata/var.sh
